GET http://localhost:5000/books HTTP/1.1

###

POST http://localhost:3500/newbook HTTP/1.1
content-type: application/json

{
    "bookImage": "https://kbimages1-a.akamaihd.net/Images/6faa402f-1a95-4897-93ff-8286cbe0e94f/255/400/False/image.jpg",
    "bookName": "1984",
    "author": "George Orwell",
    "quantity": 11,
    "department": "Historical & Criticism",
    "comments": "My favorite book"
}

###

DELETE http://localhost:5000/delete/61a6cc17289f7103357da9f6 HTTP/1.1
content-type: application/json
